### ISSUE TITLE
Health check as sub-route doesn't work

### ISSUE THREAD

**Issue by ANierbeck** [vert-x3/vertx-health-check#10]
when registering the health checks as sub-routes, the health check doesn't work as expected. 
If it's registered not as a sub-route, everything works right.

**Comment by cescoffier** [comment]
Any idea why ? Can you provide a reproducer ? BTW, subrouter are deprecated (or will be soon)

**Comment by ANierbeck** [comment]
Reproducer ... 
If you take this one: 
https://github.com/ANierbeck/Karaf-Vertx/blob/master/Vertx-AliveCheck/src/main/java/de/nierbeck/example/vertx/alive/AliveCheck.java#L87
change the route to "/ping"
but the context path to "/health"
https://github.com/ANierbeck/Karaf-Vertx/blob/master/Vertx-AliveCheck/src/main/java/de/nierbeck/example/vertx/alive/AliveCheck.java#L97
than you have a failing healthcheck. 

regarding deprecation, how will it be possible to have something similar to "sub-routes"?

**Comment by cescoffier** [comment]
About the deprecation: https://github.com/vert-x3/vertx-web/issues/462

**Comment by cescoffier** [comment]
Fixed, the id computation was wrong.

**Comment by evgeniy-maltsev** [comment]
Hello, 

please consider this gist with NullPointerException when using subrouter

https://gist.github.com/evgeniy-maltsev/b16610a08eefcd87b785d10c81b5628f

**Comment by cescoffier** [comment]
@evgeniy-maltsev Can you open another issue with your reproducer?

**Comment by evgeniy-maltsev** [comment]
@cescoffier done. https://github.com/vert-x3/vertx-health-check/issues/13
