### ISSUE TITLE
NullPointerException while serving health endpoint with subrouter

### ISSUE THREAD

**Issue by evgeniy-maltsev** [vert-x3/vertx-health-check#13]
Hello,

please consider this gist with NullPointerException when using subrouter

https://gist.github.com/evgeniy-maltsev/b16610a08eefcd87b785d10c81b5628f

**Comment by cescoffier** [comment]
The issue happens when the route has no "path".

**Comment by evgeniy-maltsev** [comment]
Ok. This piece of code:

```
    String path = rc.request().path();
    String route = rc.currentRoute().getPath();
    if (! path.startsWith(route)) {
      // We have a prefix  (sub-router)
      int indexOfRoot = path.indexOf(route);
      path = path.substring(indexOfRoot);
    }
    String id = path.substring(route.length());

```
As I see it:
`path()` and `getPath()` are clearly set as `@Nullable` and even `healthChecks.invoke(id, healthReportHandler(rc));` handles null and empty strings with no problem and returns what is expected, that is all current health checks.

This code just must check for null.

**Comment by cescoffier** [comment]
No, it's a bit more complicated (I've fixed it) in https://github.com/vert-x3/vertx-health-check/commit/17320ee67081f6c80fce31b380b561591d23c8ba

We need to use the mountPoint, request path and test whether or not the route path is `null`

**Comment by evgeniy-maltsev** [comment]
Thank for the fix! Somehow I've never saw a `mountPoint()` in RoutingContext.

**Comment by cescoffier** [comment]
@evgeniy-maltsev Shame on me... I didn't see it myself when I've implemented this feature.
