### ISSUE TITLE
HealthCheckHandler should use contentType application/json

### ISSUE THREAD

**Issue by sdavids** [vert-x3/vertx-health-check#24]
The response should have the content type `application/json` instead of `application/json;charset=UTF-8`.

See last section of: https://www.iana.org/assignments/media-types/application/json

### Version

3.8.5

### Extra

```
import static io.vertx.ext.web.client.predicate.ResponsePredicate.JSON;
import static io.vertx.ext.web.client.predicate.ResponsePredicate.SC_NO_CONTENT;

    @Test
    void testHealthEndpoint(WebClient webClient, VertxTestContext testContext) {
      webClient
          .head(port, "localhost", "/health")
          .expect(SC_NO_CONTENT)
          .expect(JSON)
          .send(testContext.completing());
    }
```

instead of:

```
import static io.vertx.ext.web.client.predicate.ResponsePredicate.SC_NO_CONTENT;
import static io.vertx.ext.web.client.predicate.ResponsePredicate.contentType;

    @Test
    void testHealthEndpoint(WebClient webClient, VertxTestContext testContext) {
      webClient
          .head(port, "localhost", "/health")
          .expect(SC_NO_CONTENT)
          .expect(contentType("application/json;charset=UTF-8"))
          .send(testContext.completing());
    }
```

**Comment by vietj** [comment]
@sdavids interested in contributing a fix ?

**Comment by tsegismont** [comment]
@sdavids this doesn't look like a bug to me: it is fine to specify the character encoding of the content

https://www.w3.org/International/articles/http-charset/index

What's the problem exactly?

**Comment by vietj** [comment]
@sdavids can you explain why it is a problem to you ?

**Comment by pmlopes** [comment]
The json RFC states:

> JSON text SHALL be encoded in Unicode.  The default encoding is UTF-8.

it's not a **MUST** so users may use different encodings UTF-8, UTF-16, etc... and in this case the charset is useful to remove ambiguity. Also it is not stated that charset is forbidden.

Can you explain why you think this is a bug?

**Comment by pmlopes** [comment]
I'll close it for now, unless this really proves to be a bug, then it can be reopen and we will follow the spec that confirms it.

**Comment by sdavids** [comment]
I do not consider it a "bug" but the spec says it should be just `application/json`.

**Comment by sdavids** [comment]
If you leave it at `application/json;charset=UTF-8` it would be helpful to have the following:

- `io.vertx.ext.web.client.predicate.ResponsePredicate.JSON_UTF8` or something that accepts both `application/json` and `application/json;charset=UTF-8`.

I do not want to litter my code with `"application/json;charset=UTF-8"` or be forced to create a constant on my own or import a third-party library just for that constant.

See the original comment on how cleaner it looks with constants.

**Comment by sdavids** [comment]
@pmlopes 

https://tools.ietf.org/html/rfc2119

"1. MUST   This word, or the terms "REQUIRED" or "SHALL", mean that the
   definition is an absolute requirement of the specification."
