### ISSUE TITLE
Manipulate the response of the health handler

### ISSUE THREAD

**Issue by marksuurland** [vert-x3/vertx-health-check#30]
#### Describe the feature

The health handler always returns the response containing the checks array and the results. Besides that it ends the response, meaning chaining another handler to do something with the result is not possible.

It would be great if the response could be manipulated. 

#### Use cases

To do analysis on the results of the healthcheck endpoints (e.g. with elastic search) having an anonymous array structure (like checks: []) is not optional, the possibility to manipulate the default result would help. 

#### Contribution

-

**Comment by vietj** [comment]
can you write a proposal and contribute it ?

**Comment by tsegismont** [comment]
@marksuurland can you elaborate about your needs? To you really want to transform the web response or only get a notification of `CheckResult` when the health check handler processes a request?

**Comment by marksuurland** [comment]
@tsegismont I think it makes sense to have some possibility to transform the default web response.

**Comment by tsegismont** [comment]
Can you expand the description with snippets then? Thanks
