### ISSUE TITLE
What license is this code under?

### ISSUE THREAD

**Issue by sophokles73** [vert-x3/vertx-health-check#7]

**Comment by cescoffier** [comment]
Apache License 2.0.

I've added the license to the repository

**Comment by sophokles73** [comment]
Thanks, mate :-)

**Comment by rainsailor** [comment]
I've question for copyright
Usually, Copyright sentense is located in source code.
But, I can't find it anywhere.

How can I notice copyright?

**Comment by vietj** [comment]
it should be EPL/ASL2
